networks:
  pulsar:
    driver: bridge
  anonimizacion:
    driver: bridge
  ingesta:
    driver: bridge
  user:
    driver: bridge

services:
  broker:
    image: apachepulsar/pulsar:2.10.2
    container_name: broker
    profiles: ["sin_anonimizacion","","sin_bff","pulsar"]
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - pulsar

  user_db:
    image: postgres:15
    container_name: postgres_db
    profiles: ["sin_anonimizacion","","sin_bff"]
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    networks:
      - user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./manejo_usuarios/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_db"]
      interval: 10s
      retries: 5
      timeout: 5s

  user_service:
    build:
      context: ./manejo_usuarios
      dockerfile: Dockerfile
    container_name: user_auth_service
    profiles: ["sin_anonimizacion","","sin_bff"]
    restart: always
    depends_on:
      user_db:
        condition: service_healthy 
    environment:
      DATABASE_URL: postgresql://user:password@user_db/user_db
    networks:
      - user
    ports:
      - "8000:8000"

  anonimizacion_service:
    build:
      context: ./anonimizacion_imagenes
      dockerfile: Dockerfile
    container_name: anonimizacion_contenedor
    profiles: ["anonimizacion","","sin_bff"]
    environment:
      - BROKER_HOST=broker
      - DB_HOSTNAME=anonimizacion_db
      - DB_PORT=5432
    ports:
      - "5001:5001"
    depends_on:
      broker:
        condition: service_healthy
      anonimizacion_db:
        condition: service_healthy
    networks:
      - anonimizacion
      - pulsar

  anonimizacion_db:
    image: postgres:15
    container_name: anonimizacion_db
    profiles: ["sin_anonimizacion","","sin_bff"]
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anonimizacion_db
    ports:
      - "9001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d anonimizacion_db"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - anonimizacion

  ingesta_db:
    image: postgres:15
    container_name: ingesta_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ingesta_db
    ports:
      - "9002:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ingesta_db"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - ingesta

  ingesta_service:
    build:
      context: ./ingesta_imagenes
      dockerfile: Dockerfile
    container_name: ingesta_contenedor
    profiles: ["sin_anonimizacion","","sin_bff"]
    environment:
      - BROKER_HOST=broker
      - DB_HOSTNAME=ingesta_db
      - DB_PORT=5432
    ports:
      - "5000:5000"
    depends_on:
      broker:
        condition: service_healthy
      ingesta_db:
        condition: service_healthy
    networks:
      - ingesta
      - pulsar

  bff_graphql:
    build:
      context: ./bff
      dockerfile: Dockerfile
    container_name: bff_graphql_contenedor
    profiles: ["bff",""]
    environment:
      - BROKER_HOST=broker
      - ANONIMIZACION_SERVICE_URL=http://anonimizacion_contenedor:5001
      - INGESTA_SERVICE_URL=http://ingesta_contenedor:5000
      - USER_AUTH_SERVICE_URL=http://user_service:8000
    ports:
      - "8001:8001"
    depends_on:
      broker:
        condition: service_healthy
      anonimizacion_service:
        condition: service_started
      ingesta_service:
        condition: service_started
    networks:
      - pulsar
      - anonimizacion
      - user

volumes:
  postgres_data:
