networks:
  pulsar:
    driver: bridge
  anonimizacion:
    driver: bridge

services:
  broker:
    image: apachepulsar/pulsar:latest
    container_name: broker
    profiles: ["sin_anonimizacion",""]
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 30

  user_db:
    image: postgres:15
    container_name: postgres_db
    profiles: ["sin_anonimizacion",""]
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./manejo_usuarios/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_db"]
      interval: 10s
      retries: 5
      timeout: 5s

  user_service:
    build:
      context: ./manejo_usuarios
      dockerfile: Dockerfile
    container_name: user_auth_service
    profiles: ["sin_anonimizacion",""]
    restart: always
    depends_on:
      user_db:
        condition: service_healthy 
    environment:
      DATABASE_URL: postgresql://user:password@user_db/user_db
    ports:
      - "8000:8000"

  anonimizacion_service:
    build:
      context: ./anonimizacion_imagenes
      dockerfile: Dockerfile
    container_name: anonimizacion_contenedor
    profiles: ["anonimizacion",""]
    environment:
      - BROKER_HOST=broker
      - DB_HOSTNAME=anonimizacion_db
      - DB_PORT=5432
    ports:
      - "5001:5001"
    depends_on:
      broker:
        condition: service_healthy
      anonimizacion_db:
        condition: service_healthy
  anonimizacion_db:
    image: postgres:15
    container_name: anonimizacion_db
    profiles: ["sin_anonimizacion",""]
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anonimizacion_db
    ports:
      - "9001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d anonimizacion_db"]
      interval: 10s
      retries: 5
      timeout: 5s

  ingesta_service:
    build:
      context: ./ingesta_imagenes
      dockerfile: Dockerfile
    container_name: ingesta_contenedor
    profiles: ["sin_anonimizacion",""]
    environment:
      - BROKER_HOST=broker
    ports:
      - "5000:5000"
    depends_on:
      broker:
        condition: service_healthy

volumes:
  postgres_data: