apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: us-central1-docker.pkg.dev/appnomonoliticas-452202/app-no-monoliticas-repo/bff:1.0
          ports:
            - containerPort: 8001
          env:
            - name: ANONIMIZACION_SERVICE_URL
              value: "http://anonimizacion-service"
            - name: INGESTA_SERVICE_URL
              value: "http://ingesta-service"
            - name: BROKER_HOST
              value: "pulsar"
            - name: USER_AUTH_SERVICE_URL
              value: "http://servicio-manejo-usuarios"
          resources:
            requests:
              memory: "200Mi"
              cpu: "400m"
            limits:
              memory: "400Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /bff/ping
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /bff/ping
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bff-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 8001
    type: HTTP
    requestPath: /bff/ping
---
kind: Service
apiVersion: v1
metadata:
  name: bff-service
  annotations:
    cloud.google.com/backend-config: '{"default": "bff-config"}'
spec:
  type: NodePort
  selector:
    app: bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
      nodePort: 30003