apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingesta
  labels:
    app: ingesta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingesta
  template:
    metadata:
      labels:
        app: ingesta
    spec:
      containers:
        - name: ingesta
          image: us-central1-docker.pkg.dev/appnomonoliticas-452202/app-no-monoliticas-repo/ingesta:2.0
          ports:
            - containerPort: 5000
          env:
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "monolitic4s-ingesta"
            - name: DB_HOSTNAME
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: BROKER_HOST
              value: "pulsar2"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
          volumeMounts:
            - name: gcp-credentials
              mountPath: /app/.keys
              readOnly: true
            - name: gcp-application-credentials
              mountPath: /var/secrets/google
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
          command:
            - "/cloud-sql-proxy"
            - "appnomonoliticas-452202:us-central1:monoliticas-ingesta-db"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/cloudsql/key.json
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
            items:
            - key: key.json
              path: key.json
        - name: gcp-application-credentials
          secret:
            secretName: gcp-credentials
            items:
            - key: key.json
              path: key.json
        - name: cloudsql-instance-credentials
          secret:
            secretName: gcp-credentials
            items:
            - key: key.json
              path: key.json
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingesta-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 5000
    type: HTTP
    requestPath: /ingesta-imagen/ping
---
kind: Service
apiVersion: v1
metadata:
  name: ingesta-service
  annotations:
    cloud.google.com/backend-config: '{"default": "ingesta-config"}'
spec:
  type: NodePort
  selector:
    app: ingesta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30002
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ingesta-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingesta
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 30